script/build-jdbc-urls.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/11)

Remove default database connection values

---

.github/workflows/run-cypress-tests.yml

In the cypress test pull request workflow, use one action which will setup the test environment and run all tests using a single action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/21)

Use env setup and test -action from tools repository

---

src/main/java/org/rutebanken/tiamat/model/hsl/AccessibilityLevelEnumeration.java
src/main/java/org/rutebanken/tiamat/model/hsl/HslAccessibilityProperties.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/HslAccessibilityPropertiesMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java
src/main/resources/db/migration/V49__add_hsl_accessibility_level.sql
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java
src/test/java/org/rutebanken/tiamat/versioning/AccessibilityAssessmentVersioningTest.java

UI will calculate and update this when needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/23)

Add accessibility level for stop place

---

.github/workflows/docker-build.yml
.github/workflows/run-java-tests.yml

Combine CI jobs under one workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/22)

Combine ci jobs under one workflow

---

src/main/java/org/rutebanken/tiamat/model/GroupOfStopPlaces.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/GroupOfStopPlacesMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/GroupOfStopPlacesObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/versioning/save/GroupOfStopPlacesSaverService.java
src/test/java/org/rutebanken/tiamat/model/GroupOfStopPlacesTest.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceGroupOfStopPlacesIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/24)

Add group of stop places location and validity

---

.github/workflows/docker-build.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/25)

Re-enable docker build on main branch push

---

src/main/resources/db/migration/R__view_for_newest_group_of_stop_places_versions.sql

A view for the latest versions of groups of stop places, so manual filtering is not needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/26)

Add view for latest versions of groups

---

src/main/java/org/rutebanken/tiamat/model/Contact.java
src/main/java/org/rutebanken/tiamat/model/Organisation.java
src/main/java/org/rutebanken/tiamat/model/OrganisationTypeEnumeration.java
src/main/java/org/rutebanken/tiamat/model/Organisation_VersionStructure.java
src/main/java/org/rutebanken/tiamat/model/StopPlace.java
src/main/java/org/rutebanken/tiamat/model/StopPlaceOrganisationRef.java
src/main/java/org/rutebanken/tiamat/model/StopPlaceOrganisationRelationshipEnumeration.java
src/main/java/org/rutebanken/tiamat/repository/OrganisationRepository.java
src/main/java/org/rutebanken/tiamat/repository/OrganisationRepositoryCustom.java
src/main/java/org/rutebanken/tiamat/repository/OrganisationRepositoryImpl.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/OrganisationFetcher.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/OrganisationUpdater.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/StopPlaceMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/operations/OrganisationOperationsBuilder.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/StopPlaceObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/StopPlaceOrganisationRefObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/service/organisation/OrganisationDeleter.java
src/main/java/org/rutebanken/tiamat/versioning/save/OrganisationVersionedSaverService.java
src/main/resources/db/migration/V50__create_organisation_tables.sql
src/test/java/org/rutebanken/tiamat/TiamatIntegrationTest.java
src/test/java/org/rutebanken/tiamat/auth/RoleAssignmentListBuilder.java
src/test/java/org/rutebanken/tiamat/repository/OrganisationRepositoryTest.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceOrganisationIntegrationTest.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java
src/test/resources/application.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/28)

Add Organisation data model and HSL specific Organisation relationships for Stop Places

---

src/main/java/org/rutebanken/tiamat/model/DisplayTypeEnumeration.java
src/main/java/org/rutebanken/tiamat/model/InfoSpot.java
src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster.java
src/main/java/org/rutebanken/tiamat/model/InfoSpotPosterRef.java
src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster_VersionStructure.java
src/main/java/org/rutebanken/tiamat/model/InfoSpotTypeEnumeration.java
src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java
src/main/java/org/rutebanken/tiamat/model/PosterSizeEnumeration.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepository.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryCustom.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotRepository.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotRepositoryCustom.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotRepositoryImpl.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsFetcher.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/InfoSpotObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/versioning/VersionIncrementor.java
src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotPosterVersionedSaverService.java
src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotVersionedSaverService.java
src/main/resources/db/migration/V46.6__add_info_spots.sql
src/test/java/org/rutebanken/tiamat/TiamatIntegrationTest.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java

Info spot implementation
Info spot poster implementation
Database migration
GraphQL API to read and write values
GraphQL tests for info spots
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)

Info spot implementation

---

src/main/java/org/rutebanken/tiamat/rest/graphql/types/InfoSpotObjectTypeCreator.java

So it generates correctly in UI repository.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/44)

Fix info spot input type

---

src/main/java/org/rutebanken/tiamat/repository/InfoSpotRepositoryCustom.java
src/main/java/org/rutebanken/tiamat/repository/InfoSpotRepositoryImpl.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/StopPlaceInfoSpotsFetcher.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/StopPlaceInterfaceCreator.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java

Allow nullable values for info spot graphql.
Add fetching of info spots for stop place graphql.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/45)

Info spot fixes

---

src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/49)

Use a more database agnostic way to catch HSL erors

---

src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/InfoSpotObjectTypeCreator.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java

Do not update reference if the poster does not change
Create a new version of poster when updating
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/51)

Fix updating existing info spot posters

---

development.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/60)

Do minor fixes to Docker Bundle downloading

---

src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/61)

Add versionComment field to Quay GraphQl definitions

---

src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/QuayInfoSpotsFetcher.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/62)

Add info spots under quays in graphql api

---

development.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/66)

Fix a regression bug in `development.sh` and make small improvements to it.

---

src/main/java/org/rutebanken/tiamat/model/ShelterEquipment_VersionStructure.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/PlaceEquipmentMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/CustomGraphQLTypes.java
src/main/resources/db/migration/V46.10__new_shelter_properties.sql
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/70)

Add shelter number and external id

---

src/main/java/org/rutebanken/tiamat/model/Quay.java
src/main/java/org/rutebanken/tiamat/model/QuayExternalLink.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/QuayMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/ExternalLinkObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/service/stopplace/StopPlaceMerger.java
src/main/java/org/rutebanken/tiamat/service/stopplace/StopPlaceQuayMerger.java
src/main/resources/db/migration/V46.12__external_links_for_quays.sql
src/test/java/org/rutebanken/tiamat/model/QuayTest.java
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

- SQL migration for the new table
- Add JPA definitions for quays and repository
- Add external links to GrpahQL API
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/74)

Add external links for Quays

---

src/main/java/org/rutebanken/tiamat/model/QuayExternalLink.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/ExternalLinkObjectTypeCreator.java
src/main/resources/db/migration/V47.1__primary_key_for_extranal_links.sql
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/79)

Expose external link ids

---

src/main/resources/db/migration/V47.2__stop_place_hsl_private_code_constraints.sql

Commit data changes before changes to schema.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/81)

Fix HSL private code data migration

---

src/main/java/org/rutebanken/tiamat/model/StopPlace.java
src/main/java/org/rutebanken/tiamat/model/StopPlaceExternalLink.java
src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java
src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java
src/main/java/org/rutebanken/tiamat/rest/graphql/mappers/StopPlaceMapper.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/ExternalLinkObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/ParentStopPlaceInputObjectTypeCreator.java
src/main/java/org/rutebanken/tiamat/rest/graphql/types/StopPlaceInterfaceCreator.java
src/main/resources/db/migration/V47.4__external_links_for_stop_places.sql
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/90)

Add external links for stop places

---

src/main/resources/db/migration/R__view_for_newest_stop_place_versions.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/95)

Add type fields to the newest StopPlace view

---

src/main/resources/db/migration/V47.6__stop_place_allow_duplicate_names.sql
src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceStopPlaceIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/98)

Allow duplicate StopPlace names

---

src/main/resources/db/migration/V47.7__parent_stop_place_hsl_private_code_constraints.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/100)

Add validation for terminal PrivateCodes
